import './globals.css'
import { Barlow } from 'next/font/google'
import { Navbar } from '@/components/Navbar'
import Head from 'next/head'
const inter = Barlow({ subsets: ['latin'] ,
weight:['300','400','500']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"><Head>
    <title>
      Code Transformer by Sumit Ahire
    </title>
    <meta
      name="description"
      content="Chatgpt based  code translator"
      key="desc"
    />
  </Head>

      <body className={inter.className}>
        <Navbar/>
        {children}</body>
    </html>
  )
}
