import './globals.css'
import { Barlow } from 'next/font/google'
import { Navbar } from '@/components/Navbar'
const inter = Barlow({ subsets: ['latin'] ,
weight:['300','400','500']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}</body>
    </html>
  )
}
